### ISSUE TITLE
performance: consider supporting "blake3-256:<ref>" digests?

### ISSUE THREAD

**Issue by rchincha** [opencontainers/image-spec#1193] opened 2024-06-27 17:52 UTC
https://github.com/BLAKE3-team/BLAKE3-specs/blob/master/blake3.pdf
^ blake3 is fast (but newer crypto) 

Would help with building and verifying images, especially large images.

**Comment by sudo-bmitch** [comment] 2024-06-27 20:35
I believe this is a duplicate of #819.

**Comment by tianon** [comment] 2024-06-28 02:21
Agreed 👍

**Closed by tianon** 2024-06-28 02:21 UTC

**Comment by rchincha** [comment] 2024-06-28 03:06
The motivation for suggesting blake3 here is mainly for perf reasons. If there is another hash - secure and faster than sha2, that is something we should consider.

**Comment by tianon** [comment] 2024-06-28 03:15
I think there are other benefits to blake3, but I'm far from the expert and I think #819 (the prior blake3 discussion which already has a lot of interesting discussion and useful links in it) is a more appropriate place to discuss further.
