### ISSUE TITLE
image-layout: addition of companion data

### ISSUE THREAD

**Issue by philips** [opencontainers/image-spec#129] opened 2016-06-08 23:49 UTC
@stevvooe introduced a new term in https://github.com/opencontainers/image-spec/pull/94#issuecomment-224483677 called "companion data" which @wking and I don't know. Instead of forking conversation over this new concept lets discuss the idea in a new issue.

**Comment by philips** [comment] 2016-06-08 23:49
@stevvooe can you fill in details on what you mean by companion data?

**Comment by stevvooe** [comment] 2016-06-09 05:07
The concept is described here: https://github.com/opencontainers/image-spec/pull/94#issuecomment-224784897.

The directory layout from #94 will require suffixes at the top-level as a format makes additions for unverified, blob associated data:

```
./blobs/sha256-abdef
./blobs/sha256-abdef.references
./blobs/sha256-abdef.conversion
./blobs/sha256-abdef.mirrors
```

If we use `./blobs/sha256-abdef/data` as the primary data storage location, these just become extra files:

```
./blobs/sha256-abdef/data
./blobs/sha256-abdef/references
./blobs/sha256-abdef/conversion
./blobs/sha256-abdef/mirrors
```

This may be interesting in regards to #59.

**Comment by philips** [comment] 2016-06-09 05:22
@stevvooe why postfix vs prefix? For example:

```
./mirrors/sha256-abdef
./conversion/sha256-abdef
```

**Comment by stevvooe** [comment] 2016-06-09 08:58
`mv ./blobs/sha256-abdef ./somewhere` vs `mv {mirrors,conversion}/sha256-abdef ./somewhere`

**Comment by wking** [comment] 2016-06-09 16:45
On Wed, Jun 08, 2016 at 10:07:29PM -0700, Stephen Day wrote:
> The directory layout from #94 will require suffixes at the top-level
> as a format makes additions for unverified, blob associated data:
> 
> ./blobs/sha256-abdef
> ./blobs/sha256-abdef.references
> ./blobs/sha256-abdef.conversion
> ./blobs/sha256-abdef.mirrors

I agree that that may be useful information, but I'd rather keep
non-CAS information outside the CAS blobs/.  How about a separate
notes/{alg}-{digest}/ for folks to dump this unverified,
blob-associated data?  Then when folks get around to putting engines
behind this, they are less likely to forget which data is CAS and
which is not.

**Comment by philips** [comment] 2016-06-09 16:52
Another advantage of keeping the CAS as a pure CAS and not co-mingling the hierarchy is that you could make the whole tree a RO mount. Where the expectation for this other data might be that it is writeable by a local system.

**Comment by vbatts** [comment] 2016-07-05 17:50
Not sure where we've left off here.

**Comment by wking** [comment] 2016-07-05 17:57
On Tue, Jul 05, 2016 at 10:50:45AM -0700, Vincent Batts wrote:
> Not sure where we've left off here. 

I think:

* There are use-cases for mutable data that's associated with CAS
  blobs [1].
* That data is not content-addressable, so it doesn't belong in CAS
  [2,3].
* There's no image-spec specified location for storing this
  information, although you could use refs.
* Not having an image-spec specified location is probably fine,
  because we also have no image-spec specified companion content.

We should probably table this until image-spec has something to say
about references, conversions, mirrors, or some other functionality
that would use companion data.  Until then, external tooling can
handle this however it likes.

[1]: https://github.com/opencontainers/image-spec/issues/129#issuecomment-224801045
[2]: https://github.com/opencontainers/image-spec/issues/129#issuecomment-224955212
[3]: https://github.com/opencontainers/image-spec/issues/129#issuecomment-224957174

**Comment by vbatts** [comment] 2016-10-06 17:23
it seems like this is a duplicate of #59

**Comment by wking** [comment] 2016-10-06 17:28
On Thu, Oct 06, 2016 at 10:23:19AM -0700, Vincent Batts wrote:
> it seems like this is a duplicate of #59

I think this is the generic issue and #59 is a particular use case.
But yeah, they're pretty close.

**Comment by stevvooe** [comment] 2017-02-03 22:49
@vbatts Do the recent changes to manifest list cover this? Things like appstream definitely fit in here.

**Comment by vbatts** [comment] 2017-03-09 16:42
@stevvooe i think so too. closing

**Closed by vbatts** 2017-03-09 16:42 UTC
Labels: reviewed/needs more information
