### ISSUE TITLE
docs: pandoc gives permission denied error

### ISSUE THREAD

**Issue by jonboulle** [opencontainers/image-spec#72] opened 2016-05-19 14:41 UTC
```
$ make docs
pandoc: /input/README.md: openFile: permission denied (Permission denied)
Makefile:30: recipe for target 'output/docs.pdf' failed
make: *** [output/docs.pdf] Error 1
```

@vbatts something simple?

**Comment by vbatts** [comment] 2016-05-19 15:38
hrm. I don't get that error... what's the host info or versions of things?

**Comment by jonboulle** [comment] 2016-05-19 15:39
what do you want the version of?

**Comment by vbatts** [comment] 2016-05-19 15:43
host OS? docker version?

**Comment by jonboulle** [comment] 2016-05-19 16:03
Version:      1.8.2-fc22
 API version:  1.20
 Package Version: docker-1.8.2-7.gitcb216be.fc22.x86_64
 Go version:   go1.5.1
 Git commit:   cb216be/1.8.2
 Built:
 OS/Arch:      linux/amd64

**Comment by philips** [comment] 2016-05-24 20:10
@vbatts @jonboulle any updates here?

**Comment by vbatts** [comment] 2016-05-24 21:12
I still can't reproduce ...

**Comment by philips** [comment] 2016-05-24 21:44
Closing. @jonboulle if you reproduce I will reopen it.

**Closed by philips** 2016-05-24 21:44 UTC
Labels: area/developer tooling, kind/bug, kind/documentation

**Comment by jonboulle** [comment] 2016-05-25 10:09
Docker bug. Upgrading to the latest one fixed it.

**Comment by ramkri123** [comment] 2017-05-04 14:22
@philips -- I do get the exact same problem with the latest opecontainers runtime-spec, details below. Would really appreciate your help.

unknown484d7ef0b631.attlocal.net:/home/ramki/go/src/github.com/opencontainers/runtime-spec->make docs
mkdir -p output/ && \
/usr/bin/docker run -it --rm -v /home/ramki/go/src/github.com/opencontainers/runtime-spec/:/input/:ro -v /home/ramki/go/src/github.com/opencontainers/runtime-spec/output/:/output/ -u 1000 vbatts/pandoc -f markdown_github -t latex -o /output/oci-runtime-spec.pdf /input/version.md /input/spec.md /input/principles.md /input/bundle.md /input/runtime.md /input/runtime-linux.md /input/config.md /input/config-linux.md /input/config-solaris.md /input/glossary.md
pandoc: /input/version.md: openFile: permission denied (Permission denied)
make: *** [output/oci-runtime-spec.pdf] Error 1

unknown484d7ef0b631.attlocal.net:/home/ramki/go/src/github.com/opencontainers/runtime-spec->uname -a
Linux unknown484d7ef0b631.attlocal.net 4.11.0-rc8 #1 SMP Sat Apr 29 19:59:45 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux

unknown484d7ef0b631.attlocal.net:/home/ramki/go/src/github.com/opencontainers/runtime-spec->docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-16.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      3a094bd/1.12.6
 Built:           Fri Apr 14 13:46:13 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-16.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      3a094bd/1.12.6
 Built:           Fri Apr 14 13:46:13 2017
 OS/Arch:         linux/amd64

Thanks,
Ramki

**Comment by vbatts** [comment] 2017-05-04 15:01
@ramkri123 interesting :-\ i'm checking. I don't get this on older docker version.
